import os
import sys
import subprocess
import urllib.request
import time
import ctypes

# Configuration
MOSQUITTO_URL = "https://mosquitto.org/files/binary/win64/mosquitto-2.0.22-install-windows-x64.exe"
MOSQUITTO_PATH = r"C:\Program Files\mosquitto"
MOSQUITTO_CONF = r"C:\Program Files\mosquitto\mosquitto.conf"
MQTT_HOST = "localhost"
MQTT_PORT = "1883"
MQTT_TOPIC = "reader/#"

# Mosquitto configuration for remote access
MOSQUITTO_CONFIG = """# Mosquitto Configuration
# Auto-generated by installer

# Listen on all interfaces for remote access
listener 1883 0.0.0.0

# Allow anonymous connections (no username/password)
allow_anonymous true

# Logging
log_dest file C:/Program Files/mosquitto/log/mosquitto.log
log_type all

# Persistence
persistence true
persistence_location C:/Program Files/mosquitto/data/
"""


def is_admin():
    """Check if running as administrator"""
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False


def run_as_admin():
    """Re-run the script as administrator"""
    ctypes.windll.shell32.ShellExecuteW(
        None, "runas", sys.executable, " ".join(sys.argv), None, 1
    )
    sys.exit(0)


def download_file(url, dest):
    """Download file with progress"""
    print(f"Downloading from {url}...")
    try:
        urllib.request.urlretrieve(url, dest)
        print("Download complete!")
        return True
    except Exception as e:
        print(f"Download failed: {e}")
        return False


def install_mosquitto():
    """Download and install Mosquitto"""
    print("\n" + "=" * 50)
    print("  Mosquitto MQTT Broker Installer")
    print("=" * 50 + "\n")

    # Check if already installed
    mosquitto_exe = os.path.join(MOSQUITTO_PATH, "mosquitto.exe")
    if os.path.exists(mosquitto_exe):
        print("Mosquitto is already installed!")
        response = input("Do you want to reinstall? (y/n): ").strip().lower()
        if response != 'y':
            return True

    # Download installer
    temp_installer = os.path.join(os.environ.get('TEMP', '.'), "mosquitto-setup.exe")
    if not download_file(MOSQUITTO_URL, temp_installer):
        return False

    # Run installer silently
    print("\nInstalling Mosquitto...")
    try:
        subprocess.run([temp_installer, "/S"], check=True)
        time.sleep(5)  # Wait for installation
        print("Mosquitto installed successfully!")
    except Exception as e:
        print(f"Installation failed: {e}")
        return False
    finally:
        # Cleanup
        if os.path.exists(temp_installer):
            os.remove(temp_installer)

    # Configure Mosquitto
    configure_mosquitto()

    # Configure Firewall
    configure_firewall()

    # Start Mosquitto service
    print("\nStarting Mosquitto service...")
    try:
        subprocess.run(["net", "stop", "mosquitto"], capture_output=True)
        subprocess.run([os.path.join(MOSQUITTO_PATH, "mosquitto.exe"), "install"], capture_output=True)
        subprocess.run(["net", "start", "mosquitto"], check=True)
        print("Mosquitto service started!")
    except Exception as e:
        print(f"Service start warning: {e}")

    return True


def configure_mosquitto():
    """Create Mosquitto configuration file for remote access"""
    print("\nConfiguring Mosquitto for remote access...")
    try:
        # Create log and data directories
        log_dir = os.path.join(MOSQUITTO_PATH, "log")
        data_dir = os.path.join(MOSQUITTO_PATH, "data")
        os.makedirs(log_dir, exist_ok=True)
        os.makedirs(data_dir, exist_ok=True)

        # Write configuration file
        with open(MOSQUITTO_CONF, 'w') as f:
            f.write(MOSQUITTO_CONFIG)
        print("Mosquitto configured successfully!")
        print("  - Remote access: enabled (0.0.0.0:1883)")
        print("  - Anonymous access: enabled")
    except Exception as e:
        print(f"Configuration warning: {e}")


def configure_firewall():
    """Add Windows Firewall rule for MQTT port 1883"""
    print("\nConfiguring Windows Firewall...")
    try:
        # Remove existing rule if any
        subprocess.run([
            "netsh", "advfirewall", "firewall", "delete", "rule",
            "name=Mosquitto MQTT"
        ], capture_output=True)

        # Add new firewall rule
        result = subprocess.run([
            "netsh", "advfirewall", "firewall", "add", "rule",
            "name=Mosquitto MQTT",
            "dir=in",
            "action=allow",
            "protocol=tcp",
            "localport=1883"
        ], capture_output=True, text=True)

        if result.returncode == 0:
            print("Firewall rule added successfully!")
            print("  - Port 1883 is now open for MQTT connections")
        else:
            print(f"Firewall warning: {result.stderr}")
    except Exception as e:
        print(f"Firewall warning: {e}")


def run_subscriber():
    """Run MQTT subscriber for reader/# topic"""
    print("\n" + "=" * 50)
    print("  MQTT Subscriber - reader/# topic")
    print("=" * 50)
    print(f"\nHost: {MQTT_HOST}")
    print(f"Port: {MQTT_PORT}")
    print(f"Topic: {MQTT_TOPIC}")
    print("\nListening for messages... (Press Ctrl+C to stop)\n")
    print("=" * 50 + "\n")

    mosquitto_sub = os.path.join(MOSQUITTO_PATH, "mosquitto_sub.exe")
    
    if not os.path.exists(mosquitto_sub):
        print("ERROR: mosquitto_sub.exe not found!")
        return

    try:
        subprocess.run([
            mosquitto_sub,
            "-h", MQTT_HOST,
            "-p", MQTT_PORT,
            "-t", MQTT_TOPIC,
            "-v"
        ])
    except KeyboardInterrupt:
        print("\nSubscriber stopped.")
    except Exception as e:
        print(f"Error: {e}")


def main():
    # Check for admin rights
    if not is_admin():
        print("Requesting administrator privileges...")
        run_as_admin()
        return

    # Install Mosquitto
    if install_mosquitto():
        print("\n" + "=" * 50)
        print("  Installation Complete!")
        print("=" * 50)

        # Show connection info
        print("\n📡 Connection Info:")
        print(f"  - Host: localhost (or your PC's IP address)")
        print(f"  - Port: {MQTT_PORT}")
        print("\n📱 To connect from Mac/MQTTX:")
        print("  1. Find this PC's IP: ipconfig")
        print("  2. Connect to: <IP>:1883")

        print("\nMosquitto service is running!")
        input("\nPress Enter to exit...")
    else:
        print("\nInstallation failed!")
        input("\nPress Enter to exit...")


if __name__ == "__main__":
    main()

